name: youtube-clone CD

on: 
  push: 
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - run: npm ci
      - name: build
        run: npm run build
        env:
          CI: false
      - uses: w9jds/firebase-action@master
        with: 
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}